export const COLORS = [
  { key: "primary", label: "Principal" },
  { key: "primary-texto", label: "Texto sobre principal" },
  { key: "secondary", label: "Secundario" },
  { key: "accent", label: "Acento" },
  { key: "fondo", label: "Fondo de página" },
  { key: "tarjeta", label: "Tarjetas" },
  { key: "texto", label: "Texto" },
  { key: "borde", label: "Bordes" },
];

export const PALETTES = [
  {
    name: "Clásica",
    tema: "claro",
    colors: {
      primary: "#1D4ED8",
      "primary-texto": "#FFFFFF",
      secondary: "#475569",
      accent: "#6D28D9",
      fondo: "#F8FAFC",
      tarjeta: "#FFFFFF",
      texto: "#0F172A",
      borde: "#E2E8F0",
    },
  },
  {
    name: "Cálida",
    tema: "claro",
    colors: {
      primary: "#92400E",
      "primary-texto": "#FFFFFF",
      secondary: "#7A4A2D",
      accent: "#0F6B5C",
      fondo: "#FFF6EE",
      tarjeta: "#FFFFFF",
      texto: "#3A2418",
      borde: "#EAD8C5",
    },
  },
  {
    name: "Rosada",
    tema: "claro",
    colors: {
      primary: "#BE185D",
      "primary-texto": "#FFFFFF",
      secondary: "#9D4D68",
      accent: "#A21CAF",
      fondo: "#FDF3F6",
      tarjeta: "#FFFFFF",
      texto: "#46111F",
      borde: "#F3D6DF",
    },
  },
  {
    name: "Violeta",
    tema: "claro",
    colors: {
      primary: "#6D28D9",
      "primary-texto": "#FFFFFF",
      secondary: "#5B4A8A",
      accent: "#9C5F07",
      fondo: "#F6F2FC",
      tarjeta: "#FFFFFF",
      texto: "#2E1A5E",
      borde: "#E5DDF2",
    },
  },
  {
    name: "Verde bosque",
    tema: "claro",
    colors: {
      primary: "#15803D",
      "primary-texto": "#FFFFFF",
      secondary: "#3F6147",
      accent: "#9A3412",
      fondo: "#F2F9F1",
      tarjeta: "#FFFFFF",
      texto: "#16271B",
      borde: "#DCEAD7",
    },
  },
  {
    name: "Esmeralda",
    tema: "claro",
    colors: {
      primary: "#0F766E",
      "primary-texto": "#FFFFFF",
      secondary: "#2E5E61",
      accent: "#BE123C",
      fondo: "#EEF8F6",
      tarjeta: "#FFFFFF",
      texto: "#0E2B29",
      borde: "#CDEAE4",
    },
  },
  {
    name: "Océano",
    tema: "claro",
    colors: {
      primary: "#075985",
      "primary-texto": "#FFFFFF",
      secondary: "#3A627E",
      accent: "#BE123C",
      fondo: "#EFF8FF",
      tarjeta: "#FFFFFF",
      texto: "#0C3247",
      borde: "#D3E7F5",
    },
  },
  {
    name: "Vino",
    tema: "claro",
    colors: {
      primary: "#881337",
      "primary-texto": "#FFFFFF",
      secondary: "#7E3A4C",
      accent: "#9C5F07",
      fondo: "#FBF0F2",
      tarjeta: "#FFFFFF",
      texto: "#3F0E1F",
      borde: "#F0D9DF",
    },
  },
  {
    name: "Dorado",
    tema: "claro",
    colors: {
      primary: "#A04E09",
      "primary-texto": "#FFFFFF",
      secondary: "#7A5E33",
      accent: "#166534",
      fondo: "#FFFAF0",
      tarjeta: "#FFFFFF",
      texto: "#3D2B12",
      borde: "#F1E4C9",
    },
  },
  {
    name: "Minimal",
    tema: "claro",
    colors: {
      primary: "#18181B",
      "primary-texto": "#FFFFFF",
      secondary: "#52525B",
      accent: "#BE123C",
      fondo: "#FFFFFF",
      tarjeta: "#FAFAFA",
      texto: "#18181B",
      borde: "#E4E4E7",
    },
  },
  {
    name: "Playful",
    tema: "claro",
    colors: {
      primary: "#BE123C",
      "primary-texto": "#FFFFFF",
      secondary: "#8A3750",
      accent: "#7C3AED",
      fondo: "#FFF4F6",
      tarjeta: "#FFFFFF",
      texto: "#43121E",
      borde: "#F6D7DE",
    },
  },
  {
    name: "Arena",
    tema: "claro",
    colors: {
      primary: "#6F4E37",
      "primary-texto": "#FDF6EC",
      secondary: "#6E5841",
      accent: "#0F766E",
      fondo: "#FAF4EA",
      tarjeta: "#FFFFFF",
      texto: "#2B2117",
      borde: "#EADFCB",
    },
  },
  {
    name: "Terra",
    tema: "intermedio",
    colors: {
      primary: "#A8502B",
      "primary-texto": "#FFFFFF",
      secondary: "#C2AE9A",
      accent: "#F09A76",
      fondo: "#463326",
      tarjeta: "#543D2E",
      texto: "#F7EEE4",
      borde: "#7A6248",
    },
  },
  {
    name: "Salvia",
    tema: "intermedio",
    colors: {
      primary: "#577B47",
      "primary-texto": "#FFFFFF",
      secondary: "#BCC6B2",
      accent: "#E2C17E",
      fondo: "#3E463A",
      tarjeta: "#4A5346",
      texto: "#F3F6EF",
      borde: "#65705F",
    },
  },
  {
    name: "Lavanda",
    tema: "intermedio",
    colors: {
      primary: "#775AAC",
      "primary-texto": "#FFFFFF",
      secondary: "#C3B4D9",
      accent: "#E9C97E",
      fondo: "#453556",
      tarjeta: "#514163",
      texto: "#F5F0FB",
      borde: "#6E5B88",
    },
  },
  {
    name: "Petróleo",
    tema: "intermedio",
    colors: {
      primary: "#1F7A8B",
      "primary-texto": "#FFFFFF",
      secondary: "#B0C6C9",
      accent: "#E8BE6C",
      fondo: "#2F4347",
      tarjeta: "#384E53",
      texto: "#EFF7F8",
      borde: "#517078",
    },
  },
  {
    name: "Café",
    tema: "intermedio",
    colors: {
      primary: "#8A5A35",
      "primary-texto": "#FFFFFF",
      secondary: "#C2AC97",
      accent: "#E5A96E",
      fondo: "#3A2C22",
      tarjeta: "#46362A",
      texto: "#F5EDE4",
      borde: "#6A5540",
    },
  },
  {
    name: "Grafito",
    tema: "intermedio",
    colors: {
      primary: "#3E6C8C",
      "primary-texto": "#FFFFFF",
      secondary: "#AFBAC2",
      accent: "#4FD1A0",
      fondo: "#333A40",
      tarjeta: "#3D454C",
      texto: "#F2F5F7",
      borde: "#566269",
    },
  },
  {
    name: "Ocre",
    tema: "intermedio",
    colors: {
      primary: "#937026",
      "primary-texto": "#FFFFFF",
      secondary: "#C4B583",
      accent: "#F0A469",
      fondo: "#463C22",
      tarjeta: "#52452A",
      texto: "#F6EFDB",
      borde: "#77683D",
    },
  },
  {
    name: "Rosado",
    tema: "intermedio",
    colors: {
      primary: "#A34561",
      "primary-texto": "#FFFFFF",
      secondary: "#D0ADB8",
      accent: "#EBC27E",
      fondo: "#4B2E36",
      tarjeta: "#563742",
      texto: "#FBF1F4",
      borde: "#7A5261",
    },
  },
  {
    name: "Oscura",
    tema: "oscuro",
    colors: {
      primary: "#534AE6",
      "primary-texto": "#FFFFFF",
      secondary: "#94A3B8",
      accent: "#22D3EE",
      fondo: "#0F172A",
      tarjeta: "#1E293B",
      texto: "#E2E8F0",
      borde: "#334155",
    },
  },
  {
    name: "Medianoche",
    tema: "oscuro",
    colors: {
      primary: "#2563EB",
      "primary-texto": "#FFFFFF",
      secondary: "#93C5FD",
      accent: "#F472B6",
      fondo: "#020617",
      tarjeta: "#0F172A",
      texto: "#E2E8F0",
      borde: "#1E293B",
    },
  },
  {
    name: "Carbón",
    tema: "oscuro",
    colors: {
      primary: "#15803D",
      "primary-texto": "#FFFFFF",
      secondary: "#A3A3A3",
      accent: "#22D3EE",
      fondo: "#09090B",
      tarjeta: "#18181B",
      texto: "#D4D4D8",
      borde: "#27272A",
    },
  },
  {
    name: "Púrpura neón",
    tema: "oscuro",
    colors: {
      primary: "#7C3AED",
      "primary-texto": "#FFFFFF",
      secondary: "#B9A8E0",
      accent: "#F0ABFC",
      fondo: "#0D0A1A",
      tarjeta: "#1C1733",
      texto: "#E9E4F5",
      borde: "#2E2650",
    },
  },
  {
    name: "Cobre",
    tema: "oscuro",
    colors: {
      primary: "#B2551F",
      "primary-texto": "#FFFFFF",
      secondary: "#A8A29E",
      accent: "#FBBF24",
      fondo: "#1C1917",
      tarjeta: "#292524",
      texto: "#E7E5E4",
      borde: "#44403C",
    },
  },
  {
    name: "Bosque nocturno",
    tema: "oscuro",
    colors: {
      primary: "#176936",
      "primary-texto": "#FFFFFF",
      secondary: "#86EFAC",
      accent: "#FBBF24",
      fondo: "#052E16",
      tarjeta: "#14532D",
      texto: "#DCFCE7",
      borde: "#166534",
    },
  },
];

export const FONT_OPTIONS = [
  { value: "", label: "Heredar (del negocio)" },
  { value: "system-ui, -apple-system, 'Segoe UI', Roboto, sans-serif", label: "Sans (sistema)" },
  { value: "'Segoe UI', system-ui, sans-serif", label: "Segoe UI" },
  { value: "Georgia, 'Times New Roman', serif", label: "Serif" },
  { value: "'Trebuchet MS', 'Segoe UI', sans-serif", label: "Trebuchet" },
  { value: "'Courier New', ui-monospace, monospace", label: "Mono" },
];

export const SHAPE_OPTIONS = {
  radio: [
    { value: "", label: "Heredar (del negocio)" },
    { value: "0px", label: "Cuadrado" },
    { value: "8px", label: "Suave" },
    { value: "16px", label: "Redondeado" },
    { value: "9999px", label: "Píldora" },
  ],
  "columnas-grid": [
    { value: "", label: "Heredar (del negocio)" },
    { value: "2", label: "2 columnas" },
    { value: "3", label: "3 columnas" },
    { value: "4", label: "4 columnas" },
  ],
};

export const CUSTOM_LABEL = "Personalizado para esta tienda";